--DDL DATA DEFINITION LANGUAGE

--CRAETE TABLE
create table stud(
stud_id number(10),
name varchar2(20),
age number(3),
gender varchar2(20)
);

SELECT * FROM stud;
DESC stud;
--ALTER TABLE
ALTER TABLE stud ADD phone NUMBER(10);
ALTER TABLE stud MODIFY name VARCHAR2(40);
ALTER TABLE stud RENAME COLUMN phone to mobile;
ALTER TABLE stud DROP COLUMN mobile;

RENAME stud to STUDENT_DETAILS;

--TRUNCATE TABLE
TRUNCATE TABLE STUDENT_DETAILS;

--DROP TABLE
DROP TABLE STUDENT_DETAILS;

SELECT * FROM STUDENT_DETAILS;

--DML DATA MANUPULATION LANGUAGE


--INSERT
INSERT INTO STUDENT_DETAILS (stud_id,name,age,gender) VALUES (101,'name1',18,'F');
INSERT INTO STUDENT_DETAILS (stud_id,name,age,gender) VALUES (102,'name2',17,'M');
INSERT INTO STUDENT_DETAILS (stud_id,name,age,gender) VALUES (103,'name3',15,'F');
INSERT INTO STUDENT_DETAILS (stud_id,name,age,gender) VALUES (104,'name4',19,'M');

--UPDATE
UPDATE STUDENT_DETAILS SET name='selva' WHERE stud_id=102;

--DELETE
DELETE FROM STUDENT_DETAILS WHERE stud_id=104;

--MERGE
CREATE TABLE S1(S1_ID NUMBER(3),S1_NAME VARCHAR2(20)); 
CREATE TABLE S2(S2_ID NUMBER(3),S2_NAME VARCHAR2(20));

SELECT * FROM S1;
SELECT * FROM S2;

INSERT INTO S1 (S1_ID,S1_NAME) VALUES (101,'SELVA');
INSERT INTO S1 (S1_ID,S1_NAME) VALUES (102,'KUMAR');

MERGE INTO S2 USING S1 ON (S1.S1_ID=S2.S2_ID) 
WHEN MATCHED THEN UPDATE SET S2.S2_NAME=S1.S1_NAME WHEN NOT MATCHED THEN INSERT VALUES (S1.S1_ID,S1.S1_NAME);

CREATE TABLE TABL1(TABL1_ID NUMBER(3),TABL1_NAME VARCHAR2(20));

INSERT INTO TABL1 (TABL1_ID,TABL1_NAME) VALUES (101,'NAME1');
INSERT INTO TABL1 (TABL1_ID,TABL1_NAME) VALUES (102,'NAME2');

SELECT * FROM TABL1;

--TCL TRANSACTION CONTROLL LANGUAGE

--COMMIT
--ROLLBACK
--SAVEPOINT
SELECT * FROM TASK1;

--ROLLBACK  - ROLLBACK UPTO LAST COMMIT POINT. THEN THE DDL IS A AUTO COMMIT,
-- COMMIT
INSERT INTO TASK1 VALUES(101,'SELVA');
INSERT INTO TASK1 VALUES(102,'SELVA');
INSERT INTO TASK1 VALUES(103,'SELVA');
INSERT INTO TASK1 VALUES(104,'SELVA');

SELECT * FROM TASK1;

DELETE  FROM TASK1 WHERE ID=101;
DELETE  FROM TASK1 WHERE ID=102;
DELETE  FROM TASK1 WHERE ID=103;
DELETE  FROM TASK1 WHERE ID=104;

SELECT * FROM TASK1;

ROLLBACK;

SELECT * FROM TASK1;

INSERT INTO TASK1 VALUES(101,'SELVA');
INSERT INTO TASK1 VALUES(102,'SELVA');
INSERT INTO TASK1 VALUES(103,'SELVA');
INSERT INTO TASK1 VALUES(104,'SELVA');

SELECT * FROM TASK1;

COMMIT;

DELETE  FROM TASK1 WHERE ID=101;
DELETE  FROM TASK1 WHERE ID=102;
DELETE  FROM TASK1 WHERE ID=103;
DELETE  FROM TASK1 WHERE ID=104;

SELECT * FROM TASK1;

ROLLBACK;

SELECT * FROM TASK1;

DELETE  FROM TASK1 WHERE ID=101;
DELETE  FROM TASK1 WHERE ID=102;
DELETE  FROM TASK1 WHERE ID=103;
DELETE  FROM TASK1 WHERE ID=104;

SELECT * FROM TASK1;

-- SAVEPOINT

INSERT INTO TASK1 VALUES(101,'SELVA');
INSERT INTO TASK1 VALUES(102,'SELVA');
SAVEPOINT T1;
INSERT INTO TASK1 VALUES(103,'SELVA');
INSERT INTO TASK1 VALUES(104,'SELVA');
SAVEPOINT T2;
INSERT INTO TASK1 VALUES(105,'SELVA');
INSERT INTO TASK1 VALUES(106,'SELVA');
SAVEPOINT T3;
INSERT INTO TASK1 VALUES(107,'SELVA');
INSERT INTO TASK1 VALUES(108,'SELVA');

SELECT * FROM TASK1;

ROLLBACK TO T2;

SELECT * FROM TASK1;

TRUNCATE TABLE TASK1;

SELECT * FROM TASK1;