a=[1,2,3,4,5]
print(a)
print(type(a))
a[0]=100
print(a)
print("*************Slicing************")
print(a[1])
print(a[-1])
print(a[0:3])
print(a[2:])
print(a[:3])
print(a[::-1])
print("**************************")
a = [1,True,'Ram',2.5,[1,2,3]]
print(a,type(a))
print(a[0]," is ",type(a[0])) 
print(a[1]," is ",type(a[1]))
print(a[2]," is ",type(a[2]))
print(a[3]," is ",type(a[3]))
print(a[4]," is ",type(a[4]))
print(a[4][1])
print(a[4][:3])
print("********** Function ***********")
a=[10,20,30,40,50]
print(a)
a.clear()
print(a)
a=[11,22,33,44,55]
b=a.copy()
print(b)
a=[15,25,35,25,55,65,25,85,95]
print(a)
print(a.count(25))
print(a.index(25))
print(len(a))
print(min(a))
print(max(a))
print(a)
a.pop()
print(a)
a.pop(0)
print(a)
a.remove(25)
print(a)
print("*******************")
a=[1,2.5,True,"selva"]
a.append("kumar")
a.append("sri")
a.append("vali")
a.append(5)
print(a)
b=["name1","name2"]
a.extend(b)
print(a)
a.insert(0,"insert particula place")
print(a)
print("******* Constructor ********")
print(list(range(5)))
print(list("tutorjoes"))
a=[20,10,30,20,40,50]
print(a)
a.sort()
print(a)
a.sort(reverse=True)
print(a)
a=["leema","beema","hema"]
print(a)
a.sort()
print(a)
a.sort(reverse=True)
print(a)
a.sort(key=len)
print(a)
