import math
print(math.sqrt(4))
print(math.ceil(1.55555))
print(math.floor(1.55555))
print(math.factorial(5))
print(math.fabs(5))
print(math.fabs(-5))
print(math.pow(2,3))
print(math.log(2))
print(math.log10(2))
print(math.pi)
print(math.e)