names={"lala","leela","mela"}
print(names)
print(type(names))
print("********************")
for i in (names):
    print(i)
print("******************")
names.add("sara")
print(names)
print("**************")
a={"vasu","dasu"}
names.update(a)
print(names)
print("*********** remove element ************")
names.remove("sara")
print(names)
names.discard("rama")
print(names)
names.pop()
print(names)
names.clear()
print(names)
print("*************************")
a={1,2,3,4,5}
b={'a','b','c','d'}
c=a.union(b)
print(c)
#a.update(b)
#print(a)
d={1,2,3,4,5}
e={6,5,7,8,9}
f=d.intersection(e)
print(f)
d.intersection_update(e)
print(d)
print("******************")
g=d.symmetric_difference(e)
print(g)
d.symmetric_difference_update(e)
print(d)
print("****************")
a={1,2,3,4,5}
b={5,6,7,8}
c=a.isdisjoint(b)
print(c)
c=a.issubset(b)
print(c)
c=a.issuperset(b)
print(c)